spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cms
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Govardhan@007}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:consentmanagement88@gmail.com}
    password: ${MAIL_PASSWORD:zbtk boqc mjnt iorj}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      resource server:
        jwt:
          issuer-uri: https://dev-m6frsjfbk7k258zu.us.auth0.com/
          audiences: https://cms-api

server:
  port: 8080

auth0:
  domain: dev-m6frsjfbk7k258zu.us.auth0.com
  management:
    client-id: xDE28l12I1qmh7PfLhcYTTpmYRlxT4DN
    client-secret: rk0bWY5FejbsbJEz-04DLtGLXLBquZ3xHSfFPQNzYYysjrhcGFrcheCbbhs9BzUt

platform:
  admin:
    emails: ${PLATFORM_ADMIN_EMAILS:consentmanagement88@gmail.com}